name: hbabelsproductions
favicon: null
layout_spectrum: 0.1453418917953968
typography_spectrum: 0.8186306895222515
title: H. B. Abels Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eae8e9'
    - '#495d5c'
    - '#91928d'
    - '#bec7be'
  brandStrength: 0.661392210284248
  lightness: 0.5693129235878587
  saturation: 0.5
  rhythmicContrast: 0.23032334935851395
purpose: []
