name: hbabelsproductions
favicon: null
layout_spectrum: 0.49791
typography_spectrum: 0.10792
title: H. B. Abels Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e20016'
    - '#ffffff'
    - '#c3c3c3'
    - '#414141'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
