name: H. B. Abels Productions
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: H. B. Abels Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eae8e9'
    - '#495d5c'
    - '#91928d'
    - '#bec7be'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
